### PR TITLE
Add command autocomplete feature

### LINKED ISSUE #53: Add command autocomplete

### PR DESCRIPTION
**Pull request by ayusht2810**
#### Summary
- Added command autocomplete feature

#### Ticket Link
Fixes #53 

**Note**: CI will be fixed after merging of PR #100

### CODE REVIEW

**Review by mickmister — APPROVED** [review]
Heads up that there are some linting errors related to unused function parameters

**Review by larkox — APPROVED** [review]

**Comment by ayusht2810** [comment]
> Heads up that there are some linting errors related to unused function parameters

@mickmister I have fixed CI in the PR https://github.com/mattermost/mattermost-plugin-msteams-meetings/pull/100

**Comment by ayusht2810** [comment]
@mickmister Should I move the PR for QA review?

**Review by AayushChaudhary0001 — APPROVED** [review]
The above PR has been tested for the following scenario:

- Checked the newly added command autocomplete feature

The PR was working fine for the mentioned condition. LGTM. Approved

**Review by raghavaggarwal2308 — APPROVED** [review]

**Pull request merged**
